name: Snake Game
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Generate snake game from commit history
        uses: Platane/snk@v2
        with:
          github_user_name: Zeycio
          outputs: dist/snake.svg
      - name: Commit and push the Snake Game SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate Snake Game SVG"
          file_pattern: dist/snake.svg
